### ISSUE TITLE
Error "Table 'wp_pronamic_pay_mollie_customers' doesn't exist"

### ISSUE THREAD

**Issue by rvdsteege** [pronamic/wp-pronamic-pay-mollie#21]
After plugin install, the following error occurs for a (test) payment:

> Could not insert Mollie customer ID: cst_XXXXXXXXXX, error: Table 'database.wp_pronamic_pay_mollie_customers' doesn't exist.

This seems to be caused by the `null === $version_option` check after the changes in https://github.com/pronamic/wp-pay-core/commit/d03bb0708ad0bad2b64b1aeeb4a74b53dd310da6.

https://github.com/pronamic/wp-pronamic-pay-mollie/blob/ba457cec96fa7ff42eb71a208a5be95c058fd3ed/src/Install.php#L38-L58

**Comment by remcotolsma** [comment]
Fixed in https://github.com/pronamic/wp-pronamic-pay-mollie/commit/ba3511097e85f5292edcf5d8d3542110ceb21374.
