### ISSUE TITLE
Add support for Billie payment method

### ISSUE THREAD

**Issue by rvdsteege** [pronamic/wp-pronamic-pay-mollie#29]
> Billie is the leading B2B Buy Now, Pay Later payment method in Germany. With Billie, business buyers get flexible payment terms while merchants receive a guaranteed payout.
> 
> Currently, Billie is only available for Mollie customers residing in Germany.

https://www.mollie.com/payments/billie

**Comment by remcotolsma** [comment]
Added in:

- https://github.com/pronamic/wp-pay-core/commit/6308ab6efc6af243fe882a07e5cf4193249984f9
- https://github.com/pronamic/wp-mollie/commit/a2b6e5846b6aaf19db661959c58860e9b804ec1b
- https://github.com/pronamic/wp-pronamic-pay-mollie/commit/59ea0a8911cbe5521c4102343c53e58963ced6ab
- https://github.com/pronamic/wp-pronamic-pay-woocommerce/commit/40f83854b4130133dbab9980330ba9c82e7f9195

**Comment by LeoOosterloo** [comment]
Deze betaalmethode is blijkbaar al 12 juni toegevoegd aan de plugin.

Voortaan wel even handig om daar voor marketing doeleinden ook even op te wijzen. Zo moet de methode ook even worden toegevoegd aan pronamicpay.com.

We ondersteunden de betaalmethode via Mollie. Maar voor welke plugins wordt dit ondersteund? Ik zie in de opmerking van @remcotolsma hierboven sowieso WooCommerde staan.
