### ISSUE TITLE
Add payment methods with `recurring` feature support

### ISSUE THREAD

**Issue by rvdsteege** [pronamic/wp-pronamic-pay-mollie#33]
From customer in internal Help Scout ticket https://secure.helpscout.net/conversation/2291715621/25842:

> We have Pronamic enabled on our WordPress site and when I go to the configuration (link via Mollie), Giropay has a green check mark. But I can't select this option with Restrict Content Pro. I can select all the other options we have enabled in Pronamic.

Apparently, we didn't have a Giropay payment method in Restrict Content Pro. I've already added the gateway in https://github.com/pronamic/wp-pronamic-pay-restrict-content-pro/commit/fe192f0c39fd04bfbd15624cc5af56f56c78a48e. However, this only allows for one-off payments as we don't add `recurring` feature support for Giropay when registering the payment methods in the Mollie gateway:

https://github.com/pronamic/wp-pronamic-pay-mollie/blob/16a8f9a7edfc216680e72c10ab83f0b81d193fde/src/Gateway.php#L128-L205

According to the Mollie documentation at https://docs.mollie.com/payments/recurring#setting-up-the-first-payment:

> The following payment methods support a first payment and are thus allowed as a value for the method parameter of a first payment: `applepay` `bancontact` `belfius` `creditcard` `eps` `giropay` `ideal` `kbc` `mybank` `paypal` `sofort`

Of the mentioned methods, we're currently only adding `recurring` feature support for the following payment methods:

1. `applepay`
2. `creditcard`
3. `paypal`

Additionally, we register separate payment methods with recurring payments support for these payments methods:

1. `bancontact` → `PaymentMethods::DIRECT_DEBIT_BANCONTACT`
2. `ideal` → `PaymentMethods::DIRECT_DEBIT_IDEAL`
3. `sofort` → `PaymentMethods::DIRECT_DEBIT_SOFORT`

This leaves us with some unsupported recurring payment methods:

1. `belfius`
2. `eps`
3. `giropay`
4. `kbc`
5.  `mybank` (but we don't support this method at all)

To add support for these payment methods, we need to:

1. add `recurring` feature support _or_;
6. add separate payment methods, like we do for Bancontact, iDEAL and SOFORT.

What do you think, @remcotolsma?

**Comment by remcotolsma** [comment]
Probably related to:

- https://github.com/pronamic/wp-pronamic-pay-mollie/issues/19

**Comment by rvdsteege** [comment]
> Probably related to: […]

It is, I just tested this:

- with Gravity Forms, the Giropay method results in a subscription being created,
- with Restrict Content Pro, no subscription is created with Giropay.

🤨

<img width="598" alt="Scherm­afbeelding 2023-07-07 om 15 35 21" src="https://github.com/pronamic/wp-pronamic-pay-mollie/assets/10371164/9fa4f521-7c86-4036-bb1c-e2d1f11c989c">

<img width="596" alt="Scherm­afbeelding 2023-07-07 om 15 35 56" src="https://github.com/pronamic/wp-pronamic-pay-mollie/assets/10371164/4d4c1320-5ddd-484f-a05b-2fcad02ce0b0">

**Comment by remcotolsma** [comment]
Discussed yesterday with @rvdsteege at @Pronamic HQ, PR is open: https://github.com/pronamic/wp-pronamic-pay-mollie/pull/34.
