### ISSUE TITLE
Failed foreign key constraints when table prefix has changed

### ISSUE THREAD

**Issue by rvdsteege** [pronamic/wp-pronamic-pay-mollie#61]
At support we received the following error message, which occurs when starting a payment:

```
Database error: Cannot add or update a child row: a foreign key constraint fails (`database`.`kft_pronamic_pay_mollie_customer_users`, CONSTRAINT `fk_customer_id` FOREIGN KEY (`customer_id`) REFERENCES `dbi_pronamic_pay_mollie_customers` (`id`) ON DELETE RESTRICT ON U), Data: {"customer_id":"9034","user_id":1}.
```

The cause of this issue seems to be that the `$table_prefix` in `wp-config.php` has changed (from `dbi_` to `kft_` in this case). Maybe we can improve upon this?

_Internal Help Scout ticket: https://secure.helpscout.net/conversation/2776487356/28066_

**Comment by remcotolsma** [comment]
Then we should detect table prefix changes? That is possible if we store the table prefix in a custom option and compare it? Changing the table prefix is ​​a fairly complex operation. WordPress administrators who start doing that should ideally also check foreign keys etc..Should we mark this as "won't fix" for now? I don't expect this to be an issue very often.

**Comment by rvdsteege** [comment]
I also don't think it's a big issue, as this is the first time we came across this AFAIK. The customer mentioned she was not aware of any changes in the table prefix, but _someone_ should know as it's a complex change indeed.

I don't think we have to track changes in the table prefix through a custom option. Closing this as "won't fix" for now.
